openapi: 3.0.0
info:
  title: Created Trip DTO Definition
  version: 1.0.0
components:
  schemas:
    CreatedTripResponse:
      type: object
      properties:
        "id":
          "type": string
          "format": uuid
        "destination":
          "type": string
        "starts_at":
          "type": string
        "ends_at":
          "type": string
        "is_confirmed":
          "type": boolean
        "emails_to_invite":
          "type": array
          "items":
            "type": string
        "owner_name":
          "type": string
        "owner_email":
          "type": string