openapi: 3.0.0
info:
  title: Planner API
  version: 1.0.0
paths:
  /trips:
    post:
      summary: Create a plan for your trip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './api/model/trip-request-payload.yaml#/components/schemas/TripRequestPayload'
      responses:
        '200':
          description: Successful created
          content:
            application/json:
              schema:
                $ref: './api/model/trip-create-response.yaml#/components/schemas/TripCreateResponse'
  /trips/{id}:
    get:
      summary: Get a created trip plan
      parameters:
        - name: id
          in: path
          description: trip ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful fetched the trip plan from db
          content:
            application/json:
              schema:
                $ref: './api/model/created-trip-response.yaml#/components/schemas/CreatedTripResponse'
        '404':
          description: trip plan not found for provided id