openapi: 3.0.0
info:
  title: Trip DTO Definition
  version: 1.0.0
components:
  schemas:
    TripDto:
      type: object
      properties:
        tripId:
          type: integer
        destination:
          type: string
        date:
          type: string
          format: date
      required:
        - destination
        - date